### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Sync1010** [AlexDev404/Aurora-v2#7]
hello i would like to know if you are still working on remixing this server i actually made a bit of progress myself i just need to fix the aurora.runtime.dll and launcher the backend is complete so if you'd like to help can you contact my discord (Jays#8924)

Just To Be Clear The Name Of My Project Hopefully Ours Soon is Prime. 

Frontend ( 0% )

Backend ( 100% )

**Comment by AlexDev404** [comment]
Hi. Yes, currently I am still working on it. I'm currently working on it at a group I created called [TrailBlaze](https://github.com/trail-blaze), [(Website)](https://trail-blaze.github.io). We have already worked on the backend and launcher and it is in fact complete. I have a small team formed and we are working on a method of connecting to the server that requires no-DLL injection, which will allow us to expand our range of supported devices to any device that supports Fortnite. I am going to release a tutorial soon about how to do this after I finish up with everything, which should hopefully stabilize the Fortnite community and nobody will attack each other for "_skidding_" (little kid way of saying the word stealing). I've opened up a [Discord](https://discord.gg/C3ahZQJnns) server actually, which you can join and request dev role if you want to help out. I'm not sure if I'll be able to help you out too much though, because there is a lot going on. But if you join our development team probably others might be of some help to you. I know a guy that can do a good launcher that might be able to help you out a lot. Ping one of the developers on the Discord server if you'd like to contact that person. When I see it I'll redirect you to him. Also if you go over to the [TrailBlaze GitHub](https://github.com/trail-blaze), we have some very useful repositories that you may use for your own personal projects (just make sure to abide by the licenses otherwise we will submit a takedown).

**Comment by AlexDev404** [comment]
> Just To Be Clear The Name Of My Project Hopefully Ours Soon is Prime.

Also what does this mean? I am unable to properly parse this sentence correctly. Could you elaborate on this?

**Comment by Sync1010** [comment]
how do i request developer

**Comment by AlexDev404** [comment]
> how do i request developer

Join the discord @Cronlol.

**Comment by Sync1010** [comment]
i did my discord is Jays#8924

**Comment by AlexDev404** [comment]
I can neither friend request your tag nor view your tag in the server.

**Comment by AlexDev404** [comment]
Closed Due to Inactivity.
